vim.cmd("highlight clear")
vim.g.colors_name = "sahmd"

local bg = "#fdefe8"
local fg = "#000000"
local comment = "#999494"
local string = "#33299b"
local constant = "#de5120"
local type_ = "#d90035"
local statement = "#d40892"
local preproc = "#721e87"
local special = "#b81694"
local todo_fg = "#ae5a3a"
local todo_bg = "#e9b4a0"
local preproc_kw = "#8389cb"
local iterator = "#9f009f"

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- Base
hi("Normal", { fg = fg, bg = bg })
hi("NormalFloat", { fg = fg, bg = "#f5e3db" })
hi("FloatBorder", { fg = comment, bg = "#f5e3db" })
hi("Cursor", { fg = bg, bg = statement })
hi("iCursor", { fg = bg, bg = statement })
hi("CursorLine", { bg = "#f2ddd3" })
hi("CursorLineNr", { fg = statement, bold = true })
hi("LineNr", { fg = "#c4b8b2" })
hi("Visual", { bg = "#e0c4b8" })
hi("Search", { fg = fg, bg = "#e9b4a0" })
hi("IncSearch", { fg = bg, bg = statement })
hi("Pmenu", { fg = fg, bg = "#f2ddd3" })
hi("PmenuSel", { fg = bg, bg = statement })
hi("StatusLine", { fg = fg, bg = "#e5cfc4" })
hi("StatusLineNC", { fg = comment, bg = "#f2ddd3" })
hi("VertSplit", { fg = "#e5cfc4" })
hi("WinSeparator", { fg = "#e5cfc4" })
hi("TabLine", { fg = comment, bg = "#e5cfc4" })
hi("TabLineSel", { fg = fg, bg = bg, bold = true })
hi("TabLineFill", { bg = "#e5cfc4" })
hi("SignColumn", { bg = bg })
hi("FoldColumn", { fg = comment, bg = bg })
hi("Folded", { fg = comment, bg = "#f2ddd3" })
hi("NonText", { fg = "#c4b8b2" })
hi("SpecialKey", { fg = "#c4b8b2" })
hi("MatchParen", { fg = statement, bg = "#e5cfc4", bold = true })
hi("Directory", { fg = preproc, bold = true })
hi("Title", { fg = type_, bold = true })
hi("ErrorMsg", { fg = type_, bold = true })
hi("WarningMsg", { fg = constant })
hi("MoreMsg", { fg = preproc })
hi("Question", { fg = preproc })
hi("DiffAdd", { bg = "#d9f0d9" })
hi("DiffChange", { bg = "#e8e0d0" })
hi("DiffDelete", { fg = type_, bg = "#f5d5d5" })
hi("DiffText", { bg = "#d0c8b8", bold = true })

-- Syntax
hi("Comment", { fg = comment, italic = true })
hi("String", { fg = string })
hi("Character", { fg = string })
hi("Number", { fg = constant })
hi("Float", { fg = constant })
hi("Boolean", { fg = constant })
hi("Constant", { fg = constant })
hi("Identifier", { fg = fg })
hi("Function", { fg = statement })
hi("Statement", { fg = statement, bold = true })
hi("Conditional", { fg = statement, bold = true })
hi("Repeat", { fg = iterator, bold = true })
hi("Operator", { fg = statement })
hi("Keyword", { fg = statement, bold = true })
hi("Exception", { fg = statement, bold = true })
hi("Label", { fg = statement })
hi("Type", { fg = type_, bold = true })
hi("StorageClass", { fg = type_, bold = true })
hi("Structure", { fg = type_, bold = true })
hi("Typedef", { fg = type_, bold = true })
hi("PreProc", { fg = preproc })
hi("Include", { fg = preproc_kw, bold = true })
hi("Define", { fg = preproc_kw, bold = true })
hi("Macro", { fg = statement })
hi("PreCondit", { fg = preproc_kw, bold = true })
hi("Special", { fg = special })
hi("SpecialChar", { fg = special })
hi("Delimiter", { fg = fg })
hi("Tag", { fg = special })
hi("Todo", { fg = todo_fg, bg = todo_bg, bold = true, italic = true })
hi("Error", { fg = type_, bold = true })
hi("Underlined", { fg = preproc, underline = true })

-- Treesitter
hi("@variable", { fg = fg })
hi("@variable.builtin", { fg = constant })
hi("@variable.parameter", { fg = fg })
hi("@constant", { fg = constant })
hi("@constant.builtin", { fg = constant })
hi("@constant.macro", { fg = constant })
hi("@string", { fg = string })
hi("@character", { fg = string })
hi("@number", { fg = constant })
hi("@boolean", { fg = constant })
hi("@float", { fg = constant })
hi("@function", { fg = statement })
hi("@function.builtin", { fg = statement })
hi("@function.macro", { fg = statement })
hi("@method", { fg = statement })
hi("@constructor", { fg = type_, bold = true })
hi("@parameter", { fg = fg })
hi("@keyword", { fg = statement, bold = true })
hi("@keyword.function", { fg = statement, bold = true })
hi("@keyword.return", { fg = statement, bold = true })
hi("@keyword.operator", { fg = statement })
hi("@conditional", { fg = statement, bold = true })
hi("@repeat", { fg = iterator, bold = true })
hi("@exception", { fg = statement, bold = true })
hi("@operator", { fg = statement })
hi("@type", { fg = type_, bold = true })
hi("@type.builtin", { fg = type_, bold = true })
hi("@type.qualifier", { fg = type_, bold = true })
hi("@namespace", { fg = preproc })
hi("@include", { fg = preproc_kw, bold = true })
hi("@field", { fg = fg })
hi("@property", { fg = fg })
hi("@comment", { fg = comment, italic = true })
hi("@punctuation", { fg = fg })
hi("@punctuation.bracket", { fg = fg })
hi("@punctuation.delimiter", { fg = fg })
hi("@punctuation.special", { fg = special })
hi("@tag", { fg = type_, bold = true })
hi("@tag.attribute", { fg = statement })
hi("@tag.delimiter", { fg = fg })
hi("@text.todo", { fg = todo_fg, bg = todo_bg, bold = true, italic = true })
hi("@text.note", { fg = preproc, bold = true })
hi("@text.warning", { fg = constant, bold = true })
hi("@text.danger", { fg = type_, bold = true })

-- LSP
hi("DiagnosticError", { fg = type_ })
hi("DiagnosticWarn", { fg = constant })
hi("DiagnosticInfo", { fg = preproc })
hi("DiagnosticHint", { fg = comment })
hi("DiagnosticVirtualTextError", { fg = type_, bg = "#f5d5d5" })
hi("DiagnosticVirtualTextWarn", { fg = constant, bg = "#f5e5d5" })
hi("DiagnosticVirtualTextInfo", { fg = preproc, bg = "#f0e5f0" })
hi("DiagnosticVirtualTextHint", { fg = comment, bg = "#f2ddd3" })
hi("LspReferenceRead", { bg = "#e5cfc4" })
hi("LspReferenceWrite", { bg = "#e5cfc4" })
hi("LspReferenceText", { bg = "#e5cfc4" })

-- Plugins
hi("NvimTreeNormal", { fg = fg, bg = "#f8e8e0" })
hi("NvimTreeFolderName", { fg = preproc })
hi("NvimTreeOpenedFolderName", { fg = preproc, bold = true })
hi("NvimTreeRootFolder", { fg = statement, bold = true })
hi("BufferLineFill", { bg = "#e5cfc4" })
hi("BufferLineBackground", { fg = comment, bg = "#e5cfc4" })
hi("BufferLineBufferSelected", { fg = fg, bg = bg, bold = true })
hi("BufferLineBufferVisible", { fg = comment, bg = "#f2ddd3" })
hi("BufferLineSeparator", { fg = "#e5cfc4", bg = "#e5cfc4" })
hi("BufferLineSeparatorSelected", { fg = "#e5cfc4", bg = bg })
hi("BufferLineSeparatorVisible", { fg = "#e5cfc4", bg = "#f2ddd3" })
hi("BufferLineIndicatorSelected", { fg = statement, bg = bg })
hi("WhichKeyFloat", { bg = "#f5e3db" })
hi("WhichKeyNormal", { bg = "#f5e3db" })
hi("TelescopeNormal", { fg = fg, bg = "#f8e8e0" })
hi("TelescopeBorder", { fg = comment, bg = "#f8e8e0" })
hi("TelescopePromptNormal", { fg = fg, bg = "#f2ddd3" })
hi("TelescopePromptBorder", { fg = comment, bg = "#f2ddd3" })
hi("TelescopeSelection", { bg = "#e5cfc4" })

-- Git signs
hi("SignifySignAdd", { fg = "#4e8a4e" })
hi("SignifySignChange", { fg = "#8a7a4e" })
hi("SignifySignDelete", { fg = type_ })
